force-app/main/default/objects/Ordering_Account__c/Ordering_Account__c.object-meta.xml
<CustomObject>
    <label>Ordering Account</label>
    <nameField>
        <displayFormat>ACC-{00000}</displayFormat>
        <label>Ordering Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordering Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordering_Account__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>Facility Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordering_Account__c/fields/Treating_Physician_Information__c.field-meta.xml
<CustomField>
    <fullName>Treating_Physician_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treating Physician Information</label>
    <referenceTo>Treating_Physician_Information__c</referenceTo>
    <relationshipLabel>Treating Physician Information</relationshipLabel>
    <relationshipName>Ordering_Account_to_Physician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordering_Account__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PAT-{00000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/MI__c.field-meta.xml
<CustomField>
    <fullName>MI__c</fullName>
    <label>Middle Initial</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>Medical Record Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Ordering_Account__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordering Account</label>
    <referenceTo>Ordering_Account__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/PatientToOrder__c.field-meta.xml
<CustomField>
    <fullName>PatientToOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PatientToOrder</label>
    <referenceTo>PatientToOrder__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Treating_Physician_Information__c.field-meta.xml
<CustomField>
    <fullName>Treating_Physician_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treating Physician Information</label>
    <referenceTo>Treating_Physician_Information__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/PatientToOrder__c.object-meta.xml
<CustomObject>
    <label>PatientToOrder</label>
    <nameField>
        <label>PatientToOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PatientToOrder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PatientToOrder__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>PatientToOrder</relationshipLabel>
    <relationshipName>PatientToOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestOrder__c/TestOrder__c.object-meta.xml
<CustomObject>
    <label>Test Order</label>
    <nameField>
        <displayFormat>ORD-{00000}</displayFormat>
        <label>Test Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestOrder__c/fields/Ordering_Account__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordering Account</label>
    <referenceTo>Ordering_Account__c</referenceTo>
    <relationshipLabel>Ordering Account</relationshipLabel>
    <relationshipName>Ordering_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestOrder__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Patient</relationshipLabel>
    <relationshipName>Patient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TestOrder__c/fields/TestMenu__c.field-meta.xml
<CustomField>
    <fullName>TestMenu__c</fullName>
    <label>Test Menu</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TestOrder__c/fields/Treating_Physician_Information__c.field-meta.xml
<CustomField>
    <fullName>Treating_Physician_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treating Physician Information</label>
    <referenceTo>Treating_Physician_Information__c</referenceTo>
    <relationshipLabel>Treating Physician Information</relationshipLabel>
    <relationshipName>Treating_Physician_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treating_Physician_Information__c/Treating_Physician_Information__c.object-meta.xml
<CustomObject>
    <label>Treating Physician Information</label>
    <nameField>
        <displayFormat>PHY-{00000}</displayFormat>
        <label>Treating Physician Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treating Physician Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treating_Physician_Information__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Treating_Physician_Information__c/fields/Ordering_Account__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordering Account</label>
    <referenceTo>Ordering_Account__c</referenceTo>
    <relationshipLabel>Ordering Account</relationshipLabel>
    <relationshipName>Physician_to_Ordering_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderTestHandler.cls
public with sharing class OrderTestHandler {

    public static Map<String, Object> parseJson(String inputString) {
        System.debug('input String: ' + inputString);
        String tempKey;
        Object tempValue;
        
        Map<String, Object> input = new Map<String, Object>();
        JSONParser parsedMap = JSON.createParser(inputString);
        
        while(parsedMap.nextToken() != null) {
            if(parsedMap.getCurrentToken() == JSONToken.FIELD_NAME) {
                tempKey = parsedMap.getText();
                parsedMap.nextToken();
                
                if(parsedMap.getCurrentToken() == JSONToken.START_OBJECT) {
                    tempValue = parseJsonObject(parsedMap);
                } else {
                    tempValue = parsedMap.getText();
                }
                
                input.put(tempKey, tempValue);
            }
        }
        
        return input;
    }
    
    public static Map<String, Object> parseJsonObject(JSONParser parser) {
        Map<String, Object> nestedMap = new Map<String, Object>();
        String nestedKey;
        Object nestedValue;
        
        while(parser.nextToken() != JSONToken.END_OBJECT) {
            if(parser.getCurrentToken() == JSONToken.FIELD_NAME) {
                nestedKey = parser.getText();
                parser.nextToken();
                
                if(parser.getCurrentToken() == JSONToken.START_OBJECT) {
                    nestedValue = parseJsonObject(parser);
                } else {
                    nestedValue = parser.getText();
                }
                
                nestedMap.put(nestedKey, nestedValue);
            }
        }
        
        return nestedMap;
    }
    public static void fillNextEmptyField(sObject obj, Object value) {
        Map<String, Object> populatedFields = obj.getPopulatedFieldsAsMap();
        // System.debug(populatedFields);
        for (Integer i = 1; i <= 5; i++) { // Adjust the limit as per your needs
            String fieldName = 'Test_Order_' + i + '__c';
            if (!populatedFields.containsKey(fieldName)) {
                obj.put(fieldName, value);
                break;
            }
        }
    }


    @AuraEnabled 
    public static String handleOrderTest(String inputString, String patientId, String physicianId, String facilityId) {

        Savepoint sp = Database.setSavepoint();

        try {      
            

            String tempKey;
            String tempValue;
            
            Map<String, Object> input = parseJson(inputString);

            

            // Check CRUD permissions
            if (!Schema.sObjectType.Patient__c.isCreateable() ||
                !Schema.sObjectType.Treating_Physician_Information__c.isCreateable() ||
                !Schema.sObjectType.Ordering_Account__c.isCreateable() ||
                !Schema.sObjectType.TestOrder__c.isCreateable() ||
                !Schema.sObjectType.PatientToOrder__c.isCreateable()) {
                return 'Error: Insufficient permissions to create records';
            }

            // Extract patient information
            Patient__c patientInfo = new Patient__c(
                FirstName__c = (String) input.get('firstName'),
                LastName__c = (String) input.get('lastName'),
                MI__c = (String) input.get('mi'),
                DOB__c = Date.valueOf((String) input.get('dob')),
                Sex__c = (String) input.get('sex'),
                MRN__c = (String) input.get('mrn'),
                Address__c = (String) ((Map<String, Object>) input.get('patientAddress')).get('street'),
                ZipCode__c = (String) ((Map<String, Object>) input.get('patientAddress')).get('postalCode'),
                City__c = (String) ((Map<String, Object>) input.get('patientAddress')).get('city'),
                State__c = (String) ((Map<String, Object>) input.get('patientAddress')).get('province'),
                Country__c = (String) ((Map<String, Object>) input.get('patientAddress')).get('country'),
                Phone__c = (String) input.get('patientPhone'),
                Email__c = (String) input.get('patientEmail')
            );
            // Insert records into Salesforce
            
            Id existingPatientId = QueryController.checkPatientAlreadyExists(patientInfo.MRN__c, patientInfo.DOB__c);
            if (existingPatientId != null) {
                patientInfo.id = existingPatientId;
                System.debug('upsert Patient ' + patientInfo.id);
                upsert patientInfo;
            } else {
                System.debug('insert Patient ' + patientInfo.id);
                insert patientInfo;
            }

            
            // Extract ordering facility information
            Ordering_Account__c orderingFacilityInfo = new Ordering_Account__c(
                FacilityName__c = (String) input.get('orderingFacilityName'),
                Address__c = (String) ((Map<String, Object>) input.get('orderingAddress')).get('street'),
                ZipCode__c = (String) ((Map<String, Object>) input.get('orderingAddress')).get('postalCode'),
                City__c = (String) ((Map<String, Object>) input.get('orderingAddress')).get('city'),
                State__c = (String) ((Map<String, Object>) input.get('orderingAddress')).get('province'),
                Country__c = (String) ((Map<String, Object>) input.get('orderingAddress')).get('country'),
                Phone__c = (String) input.get('orderingPhone'),
                Email__c = (String) input.get('orderingEmail')
                );
                System.debug('orderingFacilityInfo: ' + orderingFacilityInfo);
                

            Id existingFacilityId = QueryController.checkFacilityAlreadyExists(orderingFacilityInfo);
            if (existingFacilityId != null) {
                orderingFacilityInfo.id = existingFacilityId;
                System.debug('upsert Facility ' + orderingFacilityInfo.id);
                upsert orderingFacilityInfo;
            } else {
                System.debug('inserted Facility ' + orderingFacilityInfo.id);
                insert orderingFacilityInfo;
            }
                
            // Extract physician information
            Treating_Physician_Information__c physicianInfo = new Treating_Physician_Information__c(
                FirstName__c = (String) input.get('physicianFirstName'),
                LastName__c = (String) input.get('physicianLastName'),
                Phone__c = (String) input.get('physicianPhone'),
                Email__c = (String) input.get('physicianEmail'),
                NPI__c = (String) input.get('physicianNpi'),
                Ordering_Account__c = orderingFacilityInfo.Id
            );
            System.debug('physicianInfo: ' + physicianInfo);
            

            Id existingPhysicianId = QueryController.checkPhysicianAlreadyExists(physicianInfo.NPI__c);
            if (existingPhysicianId != null) {
                physicianInfo.id = existingPhysicianId;
                System.debug('upsert Physician ' + physicianInfo.id);
                upsert physicianInfo;
            } else {
                System.debug('inserted Physician ' + physicianInfo.id);
                insert physicianInfo;
            }

            // Create new TestOrder__c record
            TestOrder__c newObjectInfo = new TestOrder__c(
                Ordering_Account__c = orderingFacilityInfo.Id,
                Patient__c = patientInfo.Id,
                Treating_Physician_Information__c = physicianInfo.Id,
                TestMenu__c = (String) input.get('testMenu')
            );

            System.debug('newObjectInfo: ' + newObjectInfo);

            insert newObjectInfo;


            PatientToOrder__c patientToOrder = QueryController.getPatientToOrder(patientInfo.Id);
            if (patientToOrder == null) {
                patientToOrder = new PatientToOrder__c(
                    Patient__c = patientInfo.Id
                );
                insert patientToOrder;
            }

            System.debug('patientToOrder: ' + patientToOrder);

            fillNextEmptyField(patientToOrder, newObjectInfo.Id);

            System.debug('patientToOrder: ' + patientToOrder);

            update patientToOrder;

            // Add two new fields
            patientInfo.Treating_Physician_Information__c = physicianInfo.Id;
            patientInfo.Ordering_Account__c = orderingFacilityInfo.Id;
            patientInfo.patientToOrder__c = patientToOrder.Id;

            // Insert records into Salesforce
            update patientInfo;          

            return 'Form data received and saved in Salesforce';
    
        } catch (Exception e) {
            // Rollback to the savepoint if any of the inserts fail
            Database.rollback(sp);
            
            System.debug('General Exception: ' + e.getMessage());
            System.debug('Source: ' + e.getCause());
            System.debug('Stack Trace: ' + e.getStackTraceString());
            System.debug('Exception Type: ' + e.getTypeName());
            throw new AuraHandledException(e.getMessage());

        }
    }

}