force-app/main/default/objects/Ordering_Account__c/Ordering_Account__c.object-meta.xml
<CustomObject>
    <label>Ordering Account</label>
    <nameField>
        <displayFormat>ACC-{00000}</displayFormat>
        <label>Ordering Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordering Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordering_Account__c/fields/FacilityName__c.field-meta.xml
<CustomField>
    <fullName>FacilityName__c</fullName>
    <label>Facility Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ordering_Account__c/fields/Treating_Physician_Information__c.field-meta.xml
<CustomField>
    <fullName>Treating_Physician_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treating Physician Information</label>
    <referenceTo>Treating_Physician_Information__c</referenceTo>
    <relationshipLabel>Treating Physician Information</relationshipLabel>
    <relationshipName>Ordering_Account_to_Physician</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ordering_Account__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PAT-{00000}</displayFormat>
        <label>Patient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/MI__c.field-meta.xml
<CustomField>
    <fullName>MI__c</fullName>
    <label>Middle Initial</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/MRN__c.field-meta.xml
<CustomField>
    <fullName>MRN__c</fullName>
    <label>Medical Record Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Ordering_Account__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordering Account</label>
    <referenceTo>Ordering_Account__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/PatientToOrder__c.field-meta.xml
<CustomField>
    <fullName>PatientToOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PatientToOrder</label>
    <referenceTo>PatientToOrder__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Treating_Physician_Information__c.field-meta.xml
<CustomField>
    <fullName>Treating_Physician_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treating Physician Information</label>
    <referenceTo>Treating_Physician_Information__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/ZipCode__c.field-meta.xml
<CustomField>
    <fullName>ZipCode__c</fullName>
    <label>Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/PatientToOrder__c.object-meta.xml
<CustomObject>
    <label>PatientToOrder</label>
    <nameField>
        <label>PatientToOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PatientToOrder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PatientToOrder__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>PatientToOrder</relationshipLabel>
    <relationshipName>PatientToOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/fields/Test_Order_1__c.field-meta.xml
<CustomField>
    <fullName>Test_Order_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Order 1</label>
    <referenceTo>TestOrder__c</referenceTo>
    <relationshipLabel>PatientToOrder</relationshipLabel>
    <relationshipName>PatientToOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/fields/Test_Order_2__c.field-meta.xml
<CustomField>
    <fullName>Test_Order_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Order 2</label>
    <referenceTo>TestOrder__c</referenceTo>
    <relationshipLabel>PatientToOrder (Test Order 2)</relationshipLabel>
    <relationshipName>PatientToOrder1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/fields/Test_Order_3__c.field-meta.xml
<CustomField>
    <fullName>Test_Order_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Order 3</label>
    <referenceTo>TestOrder__c</referenceTo>
    <relationshipLabel>PatientToOrder (Test Order 3)</relationshipLabel>
    <relationshipName>PatientToOrder2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/fields/Test_Order_4__c.field-meta.xml
<CustomField>
    <fullName>Test_Order_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Order 4</label>
    <referenceTo>TestOrder__c</referenceTo>
    <relationshipLabel>PatientToOrder (Test Order 4)</relationshipLabel>
    <relationshipName>PatientToOrder3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PatientToOrder__c/fields/Test_Order_5__c.field-meta.xml
<CustomField>
    <fullName>Test_Order_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Order 5</label>
    <referenceTo>TestOrder__c</referenceTo>
    <relationshipLabel>PatientToOrder (Test Order 5)</relationshipLabel>
    <relationshipName>PatientToOrder4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Treating_Physician_Information__c/Treating_Physician_Information__c.object-meta.xml
<CustomObject>
    <label>Treating Physician Information</label>
    <nameField>
        <displayFormat>PHY-{00000}</displayFormat>
        <label>Treating Physician Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treating Physician Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Treating_Physician_Information__c/fields/NPI__c.field-meta.xml
<CustomField>
    <fullName>NPI__c</fullName>
    <label>NPI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Treating_Physician_Information__c/fields/Ordering_Account__c.field-meta.xml
<CustomField>
    <fullName>Ordering_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordering Account</label>
    <referenceTo>Ordering_Account__c</referenceTo>
    <relationshipLabel>Ordering Account</relationshipLabel>
    <relationshipName>Physician_to_Ordering_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QueryController.cls
public with sharing class QueryController {
    @AuraEnabled
    public static List<Patient__c> searchPatientAccounts(String patientSearchTerm) {
        try {
            System.debug('searchPatientAccount' + patientSearchTerm);
            String searchTerm = '%' + patientSearchTerm + '%';
            String query = 'SELECT Name, Id, firstName__c, mi__c, lastName__c, dob__c, sex__c, mrn__c, address__c, city__c, country__c, zipCode__c, phone__c, state__c, email__c, Treating_Physician_Information__c, Ordering_Account__c FROM Patient__c WHERE ' +
                           'firstName__c LIKE :searchTerm OR lastName__c LIKE :searchTerm or address__c LIKE: searchTerm or email__c LIKE:searchTerm or mrn__c LIKE: searchTerm';
            return Database.query(query);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Patient__c getPatientFromId(String patientId) {
        
        if (String.isBlank(patientId)) {
            System.debug('Patient ID cannot be null or empty.');
            throw new AuraHandledException('Patient ID cannot be null or empty.');
        }
        try{
            String query = 'SELECT Name, Id, firstName__c, mi__c, lastName__c, dob__c, sex__c, mrn__c, address__c, city__c, country__c, zipCode__c, phone__c, state__c, email__c, Treating_Physician_Information__c, Ordering_Account__c FROM Patient__c WHERE Id = :patientId';    
            List<Patient__c> results = Database.query(query);
            if (results != null && !results.isEmpty()) {
                return results[0];
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException('An error occurred while fetching the patient: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static Id checkPatientAlreadyExists(String mrn, Date dob){
        try {
            String query = 'SELECT Id FROM Patient__c WHERE MRN__c = :mrn AND DOB__c = :dob';
            List<Patient__c> results = Database.query(query);
            if (results != null && !results.isEmpty()) {
                return results[0].Id;
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException('An error occurred while fetching the patient: ' + e.getMessage());
        }
    }  
    
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            

    @AuraEnabled
    public static List<Treating_Physician_Information__c> searchPhysicianAccounts(String physicianSearchTerm) {
        try {
            
            String searchTerm = '%' + physicianSearchTerm + '%';
            String query = 'SELECT Name, Id, FirstName__c, LastName__c, Phone__c, Email__c, NPI__c, Ordering_Account__c FROM Treating_Physician_Information__c WHERE ' +
                    'FirstName__c LIKE :searchTerm OR LastName__c LIKE :searchTerm OR NPI__c LIKE :searchTerm';
            return Database.query(query);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }
    
    @AuraEnabled
    public static Treating_Physician_Information__c getPhysicianFromId(String physicianId) {
        if (String.isBlank(physicianId)) {
            throw new AuraHandledException('Physician ID cannot be null or empty.');
        }
        
        try {
            String query = 'SELECT Name, Id, FirstName__c, LastName__c, Phone__c, Email__c, NPI__c, Ordering_Account__c FROM Treating_Physician_Information__c WHERE Id = :physicianId';
            List<Treating_Physician_Information__c> results = Database.query(query);
            if (results != null && !results.isEmpty()) {
                System.debug('Physician: ' + results[0]);
                return results[0];
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException('An error occurred while fetching the physician: ' + e.getMessage());
        }
    }

    @AuraEnabled    
    public static Id checkPhysicianAlreadyExists(String npi){
        try {
            String query = 'SELECT Id FROM Treating_Physician_Information__c WHERE NPI__c = :npi';
            List<Treating_Physician_Information__c> results = Database.query(query);
            if (results != null && !results.isEmpty()) {
                return results[0].Id;
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException('An error occurred while fetching the physician: ' + e.getMessage());
        }
    }
    
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @AuraEnabled
    public static Ordering_Account__c getFacilityFromId(String facilityId) {
        if (String.isBlank(facilityId)) {
            System.debug('Facility ID cannot be null or empty.');
            throw new AuraHandledException('Facility ID cannot be null or empty.');
        }
        
        try {
            String query = 'SELECT Name, Id, FacilityName__c, Address__c, City__c, State__c, ZipCode__c, Country__c, Phone__c, Email__c FROM Ordering_Account__c WHERE Id = :facilityId';
            List<Ordering_Account__c> results = Database.query(query);
            if (results != null && !results.isEmpty()) {
                return results[0];
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException('An error occurred while fetching the facility: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Ordering_Account__c> searchFacilityAccounts(String facilitySearchTerm) {
        try {
            String searchTerm = '%' + facilitySearchTerm + '%';
            String query = 'SELECT Name, Id, FacilityName__c, Address__c, City__c, State__c, ZipCode__c, Country__c, Phone__c, Email__c FROM Ordering_Account__c WHERE ' +
                           'FacilityName__c LIKE :searchTerm OR Address__c LIKE :searchTerm';
            List<Ordering_Account__c> res = Database.query(query);
            return res;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    
    @AuraEnabled
    public static Id checkFacilityAlreadyExists(Ordering_Account__c orderingFacilityInfo){
        try {
            // Normalize input values
            String normalizedFacilityName = '%' + orderingFacilityInfo.FacilityName__c.toLowerCase() + '%';
            String normalizedAddress = '%' + orderingFacilityInfo.Address__c.toLowerCase() + '%';
            String normalizedZipCode = '%' + orderingFacilityInfo.ZipCode__c.toLowerCase() + '%';
            String normalizedCity = '%' + orderingFacilityInfo.City__c.toLowerCase() + '%';
            String normalizedState = '%' + orderingFacilityInfo.State__c.toLowerCase() + '%';
            String normalizedCountry = '%' + orderingFacilityInfo.Country__c.toLowerCase() + '%';

            // Construct the query
            String query = 'SELECT Id FROM Ordering_Account__c WHERE ' +
                        'FacilityName__c LIKE :normalizedFacilityName AND ' +
                        'Address__c LIKE :normalizedAddress AND ' +
                        'City__c LIKE :normalizedCity AND ' +
                        'State__c LIKE :normalizedState AND ' +
                        'ZipCode__c LIKE :normalizedZipCode AND ' +
                        'Country__c LIKE :normalizedCountry';

            // Execute the query
            List<Ordering_Account__c> results = Database.query(query);

            // Check for matching results
            if (results != null && !results.isEmpty()) {
                return results[0].Id;
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException('An error occurred while fetching the facility: ' + e.getMessage());
        }
    }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

@AuraEnabled
public static PatientToOrder__c getPatientToOrder(String patientId){
    try {
        String query = 'SELECT Id,Test_Order_1__c,Test_Order_2__c,Test_Order_3__c,Test_Order_4__c,Test_Order_5__c FROM PatientToOrder__c WHERE Patient__c = :patientId LIMIT 1';

        List<PatientToOrder__c> results = Database.query(query);
        if (results != null && !results.isEmpty()) {
            return results[0];
        }
        return null;
        
    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
}




}